export LEFT_SCREEN=DVI-D-0
export RIGHT_SCREEN=HDMI-0

ctl lock &

setxkbmap -layout gb -variant extd -option caps:super
numlockx on &

xrandr --output $LEFT_SCREEN --primary
xrandr --output $LEFT_SCREEN --left-of $RIGHT_SCREEN

xrdb -load ~/.Xresources
pulseaudio --start
# synergys --log ~/.synergy/log --debug ERROR

exec i3
